# NumPy

## NumPy Array Oluşturmak

In [33]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [203]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

### -Tek Boyutlu Array = Vektör

In [36]:
b=np.array([3.14,5,4,6]) # Bütün Arraylari Float Olarak tek Tip Tutuyor
b

array([3.14, 5.  , 4.  , 6.  ])

In [38]:
np.zeros(2,dtype=int)#

array([0, 0])

In [42]:
np.ones((2,5),dtype=int)#Matris Şeklinde Oluşturur

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
np.full((7,7),3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [37]:
np.arange(0,30,2)#0'Dan 30'a Kadar 2'Şer Artan Array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [58]:
np.linspace(0,1,5)#0 Ve 1 Arasında Eşit Uzaklıkta 5 Adet Veri

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [70]:
np.random.normal(5,1,(3,4))#Ortalaması 5, Sd Değeri 1 Olan 3,4lük bir matris 

array([[4.30087938, 4.22849261, 5.59722105, 5.33769827],
       [6.28311943, 6.32136527, 5.03615926, 5.5144191 ],
       [4.84874049, 3.90088086, 5.83264606, 5.10295263]])

In [86]:
np.random.randint(5,10,(3,3))#5ve 10 Aralığında Random İnt Değerleri

array([[7, 9, 9],
       [7, 9, 9],
       [9, 9, 7]])

## NumPy Array Özellikleri

#### **-ndim:** _Boyut Sayısı_
#### **-shape:** _Boyut Bilgisi_
#### **-size:** _Toplam Eleman Sayısı_
#### **-dtype:** _Array Veri Tipi_

In [4]:
import numpy as np

In [19]:
a=np.random.randint(0,10,(3,3))

In [21]:
a.ndim

2

In [164]:
a.shape

(3, 3)

In [23]:
a.size

9

In [168]:
a.dtype

dtype('int32')

### **-reshaping**


In [73]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [87]:
a.ndim

1

In [15]:
a=np.arange(1,10).reshape((1,9))
print(a)

[[1 2 3 4 5 6 7 8 9]]


In [17]:
a.ndim #Tek Boyutlu Bir Veriyi Çok Boyutlu Hale Getirdik

2

In [79]:
b=np.arange(1,10).reshape((3,3))#3e3lük Bir Hale Getirir
print(b)       

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
np.random.randint(15,size=(3,3,5))

array([[[ 5, 13,  0,  0, 10],
        [ 3,  8,  0, 11,  2],
        [ 5, 10,  8,  9, 12]],

       [[ 7,  1,  2,  7, 14],
        [ 0,  6,  4,  8,  0],
        [ 8,  9,  4,  0,  8]],

       [[ 4,  8,  4,  7,  7],
        [12,  3,  9,  8,  8],
        [11,  2,  6,  9,  7]]])

### **Concatenation** (Birleştirme)

In [33]:
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[1,2,3],
            [4,5,6]])

In [37]:
np.concatenate([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([a,b],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [41]:
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[7,8,9],
            [10,11,12]])

In [45]:
np.concatenate([b,a])

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

### **Split** (Array Ayırma)

In [94]:
x=np.array([1,2,3,77,77,77,3,2,1])

In [104]:
np.split(x,(3,6))

[array([1, 2, 3]), array([77, 77, 77]), array([3, 2, 1])]

In [114]:
a,b,c=np.split(x,(3,6))
print(a,b,c)

[1 2 3] [77 77 77] [3 2 1]


In [143]:
##İki Boyutlu Ayırma
#vsplit: Satıra Göre Bölme
#hsplit: Sütüna Göre Bölme

In [122]:
m=np.arange(16).reshape([4,4])
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [134]:
#Çok Boyutlu Bir Matrisi 2 Ye Bölüp Bölünen Parçayı Eklemek

In [130]:
a,b=np.vsplit(m,[2])#İkinci Satıra  Kadar Böl
print(a,b)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [141]:
np.concatenate([a,b],axis=1)

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [149]:
#Sütuna Göre Bölme

In [151]:
m=np.arange(16).reshape([4,4])
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [153]:
a,b=np.hsplit(m,[2])#İkinci Sütuna  Kadar Böl
print(a,b)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### **Sort** (Array Sıralama)

In [158]:
v=np.array([4,1,2,5,3])
print(v)

[4 1 2 5 3]


In [188]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [ ]:
#Çok Boyutlu Array Sıralama

In [228]:
m=np.random.randint(1,17,(4,4))
print(m)

[[ 5  4 16 12]
 [10  5 13  4]
 [ 1  7  4  6]
 [ 4  1  1 16]]


In [232]:
np.sort(m,axis=1) #Satırları Sıralar

array([[ 4,  5, 12, 16],
       [ 4,  5, 10, 13],
       [ 1,  4,  6,  7],
       [ 1,  1,  4, 16]])

In [234]:
np.sort(m,axis=0) #Sütunları Sıralar

array([[ 1,  1,  1,  4],
       [ 4,  4,  4,  6],
       [ 5,  5, 13, 12],
       [10,  7, 16, 16]])

### **İndex İle Elemanlara Erişim**

In [3]:
import numpy as np

In [39]:
a=np.random.randint(0,10,5)
print(a)

[7 4 7 6 8]


In [41]:
a[0]

7

In [43]:
a[-1]

8

In [47]:
a[0]=100
print(a[0])

100


In [59]:
a=np.random.randint(0,10,(2,2))
print(a)

[[8 6]
 [0 0]]


In [61]:
a[0][0]

8

In [63]:
a[1][0]

0

In [65]:
a[0][0]=1.2 #numpy Arrayi Oluşturulurken Herhangi Bir Değer
print(a)    #Float Olsaydı Tüm Değerler Float Olurdu Lakin
            #Sonradan Bir Float Değeri Girildiğinde 
            #Girilen Değer İnteger'a Yuvarlanır

[[1 6]
 [0 0]]


### **Slicing İle Array Altkümesine Erişmek