# NumPy

## NumPy Array Oluşturmak

In [3]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [203]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

### -Tek Boyutlu Array = Vektör

In [36]:
b=np.array([3.14,5,4,6]) # Bütün Arraylari Float Olarak tek Tip Tutuyor
b

array([3.14, 5.  , 4.  , 6.  ])

In [38]:
np.zeros(2,dtype=int)#

array([0, 0])

In [42]:
np.ones((2,5),dtype=int)#Matris Şeklinde Oluşturur

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
np.full((7,7),3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [37]:
np.arange(0,30,2)#0'Dan 30'a Kadar 2'Şer Artan Array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [58]:
np.linspace(0,1,5)#0 Ve 1 Arasında Eşit Uzaklıkta 5 Adet Veri

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [70]:
np.random.normal(5,1,(3,4))#Ortalaması 5, Sd Değeri 1 Olan 3,4lük bir matris 

array([[4.30087938, 4.22849261, 5.59722105, 5.33769827],
       [6.28311943, 6.32136527, 5.03615926, 5.5144191 ],
       [4.84874049, 3.90088086, 5.83264606, 5.10295263]])

In [86]:
np.random.randint(5,10,(3,3))#5ve 10 Aralığında Random İnt Değerleri

array([[7, 9, 9],
       [7, 9, 9],
       [9, 9, 7]])

## NumPy Array Özellikleri

#### **-ndim:** _Boyut Sayısı_
#### **-shape:** _Boyut Bilgisi_
#### **-size:** _Toplam Eleman Sayısı_
#### **-dtype:** _Array Veri Tipi_

In [4]:
import numpy as np

In [19]:
a=np.random.randint(0,10,(3,3))

In [21]:
a.ndim

2

In [164]:
a.shape

(3, 3)

In [23]:
a.size

9

In [168]:
a.dtype

dtype('int32')

### **-reshaping**


In [73]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [87]:
a.ndim

1

In [15]:
a=np.arange(1,10).reshape((1,9))
print(a)

[[1 2 3 4 5 6 7 8 9]]


In [17]:
a.ndim #Tek Boyutlu Bir Veriyi Çok Boyutlu Hale Getirdik

2

In [79]:
b=np.arange(1,10).reshape((3,3))#3e3lük Bir Hale Getirir
print(b)       

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
np.random.randint(15,size=(3,3,5))

array([[[ 5, 13,  0,  0, 10],
        [ 3,  8,  0, 11,  2],
        [ 5, 10,  8,  9, 12]],

       [[ 7,  1,  2,  7, 14],
        [ 0,  6,  4,  8,  0],
        [ 8,  9,  4,  0,  8]],

       [[ 4,  8,  4,  7,  7],
        [12,  3,  9,  8,  8],
        [11,  2,  6,  9,  7]]])

### **Concatenation** (Birleştirme)

In [33]:
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[1,2,3],
            [4,5,6]])

In [37]:
np.concatenate([a,b])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [39]:
np.concatenate([a,b],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [41]:
a=np.array([[1,2,3],
            [4,5,6]])
b=np.array([[7,8,9],
            [10,11,12]])

In [45]:
np.concatenate([b,a])

array([[ 7,  8,  9],
       [10, 11, 12],
       [ 1,  2,  3],
       [ 4,  5,  6]])

### **Split** (Array Ayırma)

In [94]:
x=np.array([1,2,3,77,77,77,3,2,1])

In [104]:
np.split(x,(3,6))

[array([1, 2, 3]), array([77, 77, 77]), array([3, 2, 1])]

In [114]:
a,b,c=np.split(x,(3,6))
print(a,b,c)

[1 2 3] [77 77 77] [3 2 1]


In [143]:
##İki Boyutlu Ayırma
#vsplit: Satıra Göre Bölme
#hsplit: Sütüna Göre Bölme

In [122]:
m=np.arange(16).reshape([4,4])
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [134]:
#Çok Boyutlu Bir Matrisi 2 Ye Bölüp Bölünen Parçayı Eklemek

In [130]:
a,b=np.vsplit(m,[2])#İkinci Satıra  Kadar Böl
print(a,b)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [141]:
np.concatenate([a,b],axis=1)

array([[ 0,  1,  2,  3,  8,  9, 10, 11],
       [ 4,  5,  6,  7, 12, 13, 14, 15]])

In [149]:
#Sütuna Göre Bölme

In [151]:
m=np.arange(16).reshape([4,4])
print(m)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [153]:
a,b=np.hsplit(m,[2])#İkinci Sütuna  Kadar Böl
print(a,b)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### **Sort** (Array Sıralama)

In [158]:
v=np.array([4,1,2,5,3])
print(v)

[4 1 2 5 3]


In [188]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [ ]:
#Çok Boyutlu Array Sıralama

In [228]:
m=np.random.randint(1,17,(4,4))
print(m)

[[ 5  4 16 12]
 [10  5 13  4]
 [ 1  7  4  6]
 [ 4  1  1 16]]


In [232]:
np.sort(m,axis=1) #Satırları Sıralar

array([[ 4,  5, 12, 16],
       [ 4,  5, 10, 13],
       [ 1,  4,  6,  7],
       [ 1,  1,  4, 16]])

In [234]:
np.sort(m,axis=0) #Sütunları Sıralar

array([[ 1,  1,  1,  4],
       [ 4,  4,  4,  6],
       [ 5,  5, 13, 12],
       [10,  7, 16, 16]])

### **İndex İle Elemanlara Erişim**

In [7]:
import numpy as np

In [39]:
a=np.random.randint(0,10,5)
print(a)

[7 4 7 6 8]


In [41]:
a[0]

7

In [43]:
a[-1]

8

In [47]:
a[0]=100
print(a[0])

100


In [59]:
a=np.random.randint(0,10,(2,2))
print(a)

[[8 6]
 [0 0]]


In [61]:
a[0][0]

8

In [63]:
a[1][0]

0

In [65]:
a[0][0]=1.2 #numpy Arrayi Oluşturulurken Herhangi Bir Değer
print(a)    #Float Olsaydı Tüm Değerler Float Olurdu Lakin
            #Sonradan Bir Float Değeri Girildiğinde 
            #Girilen Değer İnteger'a Yuvarlanır

[[1 6]
 [0 0]]


### **Slicing İle Array Altkümesine Erişmek**

In [9]:
a=np.arange(30,40)
print(a)

[30 31 32 33 34 35 36 37 38 39]


In [55]:
a[0:3]

array([30, 31, 32])

In [15]:
a[0:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [18]:
a[0::2] #İkişer Atlayarak İlerler

array([30, 32, 34, 36, 38])

#### İki Boyutlu Slice İşlemi

In [39]:
m=np.random.randint(0,35,size=(3,3))
print(m)

[[10 30  4]
 [18 19 29]
 [10 22 27]]


In [41]:
m[:,1:3]

array([[30,  4],
       [19, 29],
       [22, 27]])

In [59]:
m[:,0:1]

array([[10],
       [18],
       [10]])

### **Alt Küme İşlemleri**

In [63]:
a=np.random.randint(50,70,size=(6,6))
print(a)

[[55 68 67 57 68 68]
 [52 56 61 58 52 54]
 [51 51 53 58 64 61]
 [62 63 60 67 64 67]
 [65 52 55 64 67 60]
 [64 51 58 64 61 63]]


In [67]:
alt_a=a[0:2,2:4]
print(alt_a)

[[67 57]
 [61 58]]


In [77]:
alt_a[0,0]=777
alt_a[1,:]=123,456
print(alt_a)

[[777  57]
 [123 456]]


In [81]:
print(a)#Başka Bir Arraya Aktardığımız Veri
        #Üzerinde Yaptığımız Değişikler Ana 
        #Arrayimiz Üzerindede Değişmektedir

[[ 55  68 777  57  68  68]
 [ 52  56 123 456  52  54]
 [ 51  51  53  58  64  61]
 [ 62  63  60  67  64  67]
 [ 65  52  55  64  67  60]
 [ 64  51  58  64  61  63]]


In [113]:
b=np.random.randint(10,20,size=(4,4))
print(b)

[[19 15 13 12]
 [19 14 11 19]
 [11 16 15 17]
 [17 19 19 19]]


In [115]:
alt_b=b[1:3,1:3].copy()
print(alt_b)

[[14 11]
 [16 15]]


In [117]:
alt_b[0,0]=88888
print(alt_b)

[[88888    11]
 [   16    15]]


In [123]:
print(b)#.copy Metodu Kullanıldığında Bu Sorun
        #Yaşanmamaktadır

[[19 15 13 12]
 [19 14 11 19]
 [11 16 15 17]
 [17 19 19 19]]


### **Fancy İndex İle Elemanlara Erişmek**

In [139]:
a=np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [141]:
degerler=[1,4,7]

In [143]:
a[degerler]

array([1, 4, 7])

In [137]:
#İki Boyutta Fancy İndexing

In [181]:
b=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [185]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [187]:
b[satir,sutun]

array([1, 5])

### **Koşullu Eleman İşlemleri**

In [210]:
a=np.arange(1,6)
print(a)

[1 2 3 4 5]


In [212]:
a<4

array([ True,  True,  True, False, False])

In [214]:
a[a<4]

array([1, 2, 3])

In [218]:
a**2

array([ 1,  4,  9, 16, 25])

In [222]:
a/10

array([0.1, 0.2, 0.3, 0.4, 0.5])

### **Matamatiksel İşlemler**

In [18]:
v=np.array([1,2,3,4])


In [ ]:
#ufunc

In [28]:
np.add(v,1)#v+1

array([2, 3, 4, 5])

In [30]:
np.subtract(v,1)#v-1

array([0, 1, 2, 3])

In [34]:
np.power(v,3)#v**3

array([ 1,  8, 27, 64], dtype=int32)

In [38]:
np.mod(v,2)#v%2

array([1, 0, 1, 0], dtype=int32)

In [40]:
np.absolute(np.array([-6]))#Mutlak Değer Alma Fonksiyonu

array([6])

In [42]:
np.sin(360)

0.9589157234143065

In [44]:
np.log(v)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

#### İki Bilinmeyenli Denklem Çözümü

##### __4*x0 - x1=10__
##### __5*x0 + 7x1=15__

In [60]:
a=np.array([[4,-1],[5,7]])
b=np.array([10,15])


In [62]:
np.linalg.solve(a,b)

array([2.57575758, 0.3030303 ])