# **Pandas**

In [197]:
import pandas as pd
import numpy as np

### **Pandas Serisi Oluşturma**

In [37]:
pd.Series([5,6,7,8,"abc"])

0      5
1      6
2      7
3      8
4    abc
dtype: object

In [126]:
a=pd.Series([5,6,7,8,9])
type(serie)

pandas.core.series.Series

In [132]:
a.index

RangeIndex(start=0, stop=5, step=1)

In [130]:
a.axes#İndex Bilgiler

[RangeIndex(start=0, stop=5, step=1)]

In [63]:
a.dtype

dtype('int64')

In [65]:
a.ndim

1

In [73]:
a.values#İndexler Olmadan Sadece Değerleri Getirir

array([5, 6, 7, 8, 9], dtype=int64)

In [77]:
a.head(2)#İlk 2 Değeri Getirir

0    5
1    6
dtype: int64

In [81]:
a.tail(2)#Son 2 Değeri Getirir

3    8
4    9
dtype: int64

In [91]:
b=pd.Series([77,88,99,22],index=["a","b","c","d"])
print(b)#İndexlerin İsimlerinin Değiştirilmesi


a    77
b    88
c    99
d    22
dtype: int64


In [89]:
b["c"]

99

In [93]:
b["a":"c"]

a    77
b    88
c    99
dtype: int64

In [101]:
#Sözlük Üzerinden Liste Oluşturma

In [103]:
deger={"Reg":10,"Log":5}

In [109]:
sozluk=pd.Series(deger)
print(sozluk)

Reg    10
Log     5
dtype: int64


In [113]:
pd.concat([sozluk,sozluk])

Reg    10
Log     5
Reg    10
Log     5
dtype: int64

### **Seride Eleman İşlemleri**

In [124]:
a=np.array([1,2,3,4,5])
b=pd.Series(a)
print(b)

0    1
1    2
2    3
3    4
4    5
dtype: int32


In [136]:
seri=pd.Series([111,222,333],index=("Aa","Bb","Cc"))
print(seri)

Aa    111
Bb    222
Cc    333
dtype: int64


In [138]:
seri.index

Index(['Aa', 'Bb', 'Cc'], dtype='object')

In [140]:
seri.keys

<bound method Series.keys of Aa    111
Bb    222
Cc    333
dtype: int64>

In [144]:
list(seri.items())

[('Aa', 111), ('Bb', 222), ('Cc', 333)]

In [146]:
seri.values

array([111, 222, 333], dtype=int64)

In [154]:
#Eleman Sorgusu

In [160]:
"Cc" in seri #"Cc" İndexi Seride Var Mı Sorgusu

True

In [162]:
#Fancy Eleman Seçimi

In [164]:
seri[["Cc","Bb"]]

Cc    333
Bb    222
dtype: int64

In [166]:
seri["Aa":"Cc"]

Aa    111
Bb    222
Cc    333
dtype: int64

In [168]:
#Eleman Değeri Değiştirme

In [170]:
seri["Aa"]=99999
print(seri)

Aa    99999
Bb      222
Cc      333
dtype: int64


### **DataFrame Oluşturma**

In [177]:
l=(111,222,333)
print(l)

(111, 222, 333)


222

In [183]:
pd.DataFrame(l,columns=["Variables"],index=["a","b","c"])

Variables
a        111
b        222
c        333

In [193]:
#İsimlendirme Değişiklikleri

In [212]:
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [226]:
df=pd.DataFrame(a,columns=["a","b","c"],index=(1,2,3))
print(df)

   a  b  c
1  1  2  3
2  4  5  6
3  7  8  9


In [232]:
df.columns=["col1","col2","col3"]
print(df)

   col1  col2  col3
1     1     2     3
2     4     5     6
3     7     8     9


In [234]:
df.shape

(3, 3)

In [236]:
df.size

9

In [240]:
v=df.values
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [244]:
type(v)#DataFrame Tipindeki Verideki Değerleri Numpy 
       #Arrayi Olarak Getirir

numpy.ndarray

In [246]:
df.head(2)

col1  col2  col3
1     1     2     3
2     4     5     6

In [248]:
df.tail(1)

col1  col2  col3
3     7     8     9

### **DataFramde Eleman İşlemeri**