# **Pandas**

In [92]:
import pandas as pd
import numpy as np

### **Pandas Serisi Oluşturma**

In [37]:
pd.Series([5,6,7,8,"abc"])

0      5
1      6
2      7
3      8
4    abc
dtype: object

In [126]:
a=pd.Series([5,6,7,8,9])
type(serie)

pandas.core.series.Series

In [132]:
a.index

RangeIndex(start=0, stop=5, step=1)

In [130]:
a.axes#İndex Bilgiler

[RangeIndex(start=0, stop=5, step=1)]

In [63]:
a.dtype

dtype('int64')

In [65]:
a.ndim

1

In [73]:
a.values#İndexler Olmadan Sadece Değerleri Getirir

array([5, 6, 7, 8, 9], dtype=int64)

In [77]:
a.head(2)#İlk 2 Değeri Getirir

0    5
1    6
dtype: int64

In [81]:
a.tail(2)#Son 2 Değeri Getirir

3    8
4    9
dtype: int64

In [91]:
b=pd.Series([77,88,99,22],index=["a","b","c","d"])
print(b)#İndexlerin İsimlerinin Değiştirilmesi


a    77
b    88
c    99
d    22
dtype: int64


In [89]:
b["c"]

99

In [93]:
b["a":"c"]

a    77
b    88
c    99
dtype: int64

In [101]:
#Sözlük Üzerinden Liste Oluşturma

In [103]:
deger={"Reg":10,"Log":5}

In [109]:
sozluk=pd.Series(deger)
print(sozluk)

Reg    10
Log     5
dtype: int64


In [113]:
pd.concat([sozluk,sozluk])

Reg    10
Log     5
Reg    10
Log     5
dtype: int64

### **Seride Eleman İşlemleri**

In [124]:
a=np.array([1,2,3,4,5])
b=pd.Series(a)
print(b)

0    1
1    2
2    3
3    4
4    5
dtype: int32


In [136]:
seri=pd.Series([111,222,333],index=("Aa","Bb","Cc"))
print(seri)

Aa    111
Bb    222
Cc    333
dtype: int64


In [138]:
seri.index

Index(['Aa', 'Bb', 'Cc'], dtype='object')

In [140]:
seri.keys

<bound method Series.keys of Aa    111
Bb    222
Cc    333
dtype: int64>

In [144]:
list(seri.items())

[('Aa', 111), ('Bb', 222), ('Cc', 333)]

In [146]:
seri.values

array([111, 222, 333], dtype=int64)

In [154]:
#Eleman Sorgusu

In [160]:
"Cc" in seri #"Cc" İndexi Seride Var Mı Sorgusu

True

In [162]:
#Fancy Eleman Seçimi

In [164]:
seri[["Cc","Bb"]]

Cc    333
Bb    222
dtype: int64

In [166]:
seri["Aa":"Cc"]

Aa    111
Bb    222
Cc    333
dtype: int64

In [168]:
#Eleman Değeri Değiştirme

In [170]:
seri["Aa"]=99999
print(seri)

Aa    99999
Bb      222
Cc      333
dtype: int64


### **DataFrame Oluşturma**

In [177]:
l=(111,222,333)
print(l)

(111, 222, 333)


222

In [183]:
pd.DataFrame(l,columns=["Variables"],index=["a","b","c"])

Variables
a        111
b        222
c        333

In [193]:
#İsimlendirme Değişiklikleri

In [212]:
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [226]:
df=pd.DataFrame(a,columns=["a","b","c"],index=(1,2,3))
print(df)

   a  b  c
1  1  2  3
2  4  5  6
3  7  8  9


In [232]:
df.columns=["col1","col2","col3"]
print(df)

   col1  col2  col3
1     1     2     3
2     4     5     6
3     7     8     9


In [234]:
df.shape

(3, 3)

In [236]:
df.size

9

In [240]:
v=df.values
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [244]:
type(v)#DataFrame Tipindeki Verideki Değerleri Numpy 
       #Arrayi Olarak Getirir

numpy.ndarray

In [246]:
df.head(2)

col1  col2  col3
1     1     2     3
2     4     5     6

In [248]:
df.tail(1)

col1  col2  col3
3     7     8     9

### **DataFramde Eleman İşlemeri**

In [179]:
v1=np.random.randint(10,size=6)
v2=np.random.randint(10,size=6)
v3=np.random.randint(10,size=6)
dic={"v1":v1,"v2":v2,"v3":v3}
print(dic)

{'v1': array([8, 3, 3, 5, 2, 2]), 'v2': array([9, 7, 6, 8, 0, 1]), 'v3': array([0, 7, 0, 0, 9, 7])}


In [181]:
df=pd.DataFrame(dic)
print(df)

   v1  v2  v3
0   8   9   0
1   3   7   7
2   3   6   0
3   5   8   0
4   2   0   9
5   2   1   7


In [183]:
df.drop(3,axis=0)#Yapılan Drop İşlemi Kaydedilmez

v1  v2  v3
0   8   9   0
1   3   7   7
2   3   6   0
4   2   0   9
5   2   1   7

In [111]:
df

v1  v2  v3
0   7   2   2
1   6   0   3
2   2   5   4
3   0   3   3
4   7   9   3
5   8   3   2

In [185]:
df.drop(3,axis=0,inplace=True)
df  #inplace Komutu Yapılan İşlemi Kaydeder

v1  v2  v3
0   8   9   0
1   3   7   7
2   3   6   0
4   2   0   9
5   2   1   7

In [128]:
"v1" in df

True

In [187]:
l=["v1","v2","v4"]

In [157]:
for i in l:
    print(i in df)

True
True
False


In [189]:
df["v4"]=df["v2"]/df["v1"]
df #v4 Gözlemi Olmadığı İçin Yeni Bir Gözlem Oluşturdu

v1  v2  v3        v4
0   8   9   0  1.125000
1   3   7   7  2.333333
2   3   6   0  2.000000
4   2   0   9  0.000000
5   2   1   7  0.500000

In [191]:
df.drop("v4",axis=1,inplace=True)
print(df)

   v1  v2  v3
0   8   9   0
1   3   7   7
2   3   6   0
4   2   0   9
5   2   1   7


### **Gözlem/Değişken Seçimi(loc/iloc)**

In [263]:
r=np.random.randint(10,size=(10,3))
print(r)

[[2 9 6]
 [1 3 6]
 [6 6 2]
 [9 4 6]
 [3 9 0]
 [8 6 7]
 [3 2 5]
 [6 0 0]
 [1 1 6]
 [6 5 6]]


In [265]:
df=pd.DataFrame(r,columns=["v1","v2","v3"])
df

v1  v2  v3
0   2   9   6
1   1   3   6
2   6   6   2
3   9   4   6
4   3   9   0
5   8   6   7
6   3   2   5
7   6   0   0
8   1   1   6
9   6   5   6

#### iloc=Alıştığımız Şekilde İndeksleme yapar

In [283]:
df.iloc[1:3]#1den3'e Kadar 3 Dahil Değil

v1  v2  v3
1   1   3   6
2   6   6   2

In [289]:
df.iloc[0:3,0:2]

v1  v2
0   2   9
1   1   3
2   6   6

#### loc=Tanımladığımız Şekilde İndeksleme yapar

In [271]:
df.loc[1:3]#1den3'e Kadar 3 Dahil

v1  v2  v3
1   1   3   6
2   6   6   2
3   9   4   6

In [291]:
df.loc[1:2,"v1"]

1    1
2    6
Name: v1, dtype: int32

In [ ]:
df.iloc[1:2,"v1"]#Bu Komut Çalışmaz

In [294]:
df.iloc[1:2,2]

1    6
Name: v3, dtype: int32

### **Koşullu Eleman İşlemleri**

In [8]:
r=np.random.randint(10,size=(10,3))
df=pd.DataFrame(r,columns=["Var1","Var2","Var3"])
df

Var1  Var2  Var3
0     2     1     8
1     1     0     6
2     7     0     3
3     7     3     2
4     2     5     7
5     4     8     3
6     5     8     3
7     0     6     4
8     8     0     9
9     6     2     4

In [16]:
df["Var1"][3]

7

In [34]:
df.loc[2,"Var3"]

3

In [36]:
df[df.Var1>5]

Var1  Var2  Var3
2     7     0     3
3     7     3     2
8     8     0     9
9     6     2     4

In [38]:
df[df.Var1>5]["Var1"]

2    7
3    7
8    8
9    6
Name: Var1, dtype: int32

In [40]:
df[(df.Var1>5)&(df.Var1<8)]

Var1  Var2  Var3
2     7     0     3
3     7     3     2
9     6     2     4

In [ ]:
df[(df.Var1>5)&(df.Var1<8),["Var1","Var2"]]#Bu Komut Hata Verir

In [42]:
df.loc[(df.Var1>5)&(df.Var1<8),["Var1","Var2"]]

Var1  Var2
2     7     0
3     7     3
9     6     2

In [44]:
#Yada

In [60]:
df[(df.Var1>5)&(df.Var1<8)][["Var1","Var2"]]

Var1  Var2
2     7     0
3     7     3
9     6     2

### **Join(Birleştirme)İşlemleri**

In [6]:
r=np.random.randint(10,size=(4,3))
df1=pd.DataFrame(r,columns=["Var1","Var2","Var3"])
df1

Var1  Var2  Var3
0     2     3     3
1     6     4     8
2     4     3     0
3     0     7     2

In [8]:
df2=df1+100
df2

Var1  Var2  Var3
0   102   103   103
1   106   104   108
2   104   103   100
3   100   107   102

In [84]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis.

Allows optional set logic along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
  

In [77]:
pd.concat([df1,df2],axis=1)

Var1  Var2  Var3  Var1  Var2  Var3
0     6     0     2   106   100   102
1     3     4     4   103   104   104
2     2     9     7   102   109   107
3     1     0     6   101   100   106

In [88]:
pd.concat([df1,df2],ignore_index=True)

Var1  Var2  Var3
0     6     0     2
1     3     4     4
2     2     9     7
3     1     0     6
4   106   100   102
5   103   104   104
6   102   109   107
7   101   100   106

In [92]:
df1.columns=["Var1","Var2","Degisken"]

In [100]:
pd.concat([df1,df2])#Sütun İsimleri Farklı Olduğu İçin Hata Verir

TypeError: 'function' object is not subscriptable

In [12]:
pd.concat([df1,df2],join="inner")#Farklı Değişken Olmadan Birleiştirir

Var1  Var2  Var3
0     2     3     3
1     6     4     8
2     4     3     0
3     0     7     2
0   102   103   103
1   106   104   108
2   104   103   100
3   100   107   102

### **İleri Birleştirme İşlemleri**

In [29]:
#Birebir Birleştirme

In [22]:
grup = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],
                    'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

grup

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [25]:
giris = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],
                    'ilk_giris': [2010, 2009, 2014, 2019]})
giris

calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [31]:
pd.merge(grup,giris)

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [35]:
pd.merge(grup,giris,on="calisanlar")#calisanlar Değişkenine Göre Birleştirme

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [37]:
#Many To One Birleştirme

In [39]:
df=pd.merge(grup,giris)
df

calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [42]:
mudur=pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],
                    'mudur': ['Caner', 'Mustafa', 'Berkcan']})
mudur

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [44]:
pd.merge(df,mudur)

calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [48]:
#Many To Many Birleştirme

In [51]:
yetenek = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

yetenek

grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [53]:
grup

calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [55]:
pd.merge(grup,yetenek)

calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

## **!Toplulaştırma(Aggregation) Ve Gruplama(Grouping)!**

Basit toplulaştırma fonksiyonları:

* count():   Değişkendeki Değerleri Sayar
* first()
* last()
* mean():     Ortalama
* median():   Medyan 
* min():      Minumum Değer
* max():     Maximum Değer
* std():      Standart Sapma 
* var(): Varyans 
* sum(): Toplam
* describe(): Tüm Değişkenlerin Betimsel İstatistiğini Verir

In [65]:
import seaborn as sns

In [72]:
df=sns.load_dataset("planets")
df.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [74]:
df.shape

(1035, 6)

In [82]:
df["mass"].mean()#mass Değişkeninin Ortalama Değeri

2.6381605847953216

In [133]:
df.describe().T#Transpose Alma İşlemi Bu Şekilde Olur

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [139]:
df.dropna().describe().T #na Değerlerini Yok Sayar

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0